### ISSUE TITLE
Suggestion：add gui or Sound effects to the Fermentation Vessel？

### ISSUE THREAD

**Issue by Mysitia** [Heccology/Bountiful-Fares#10]
At present, it seems that determining whether fermentation is complete depends entirely on the player's experience - it is difficult for inexperienced players to determine whether it is complete.
Adding a gui to the Fermentation Vessel will make the fermentation process more transparent, while adding sound effects will be easier.

Anyway, this is just a suggestion - whether to add it or not depends entirely on your opinion.
My English is not very good, the content of this issue was translated by a translator.
I am very sorry if it has caused you any inconvenience.

This mod is great, I really like it. Looking forward to you continuing to develop more interesting content!

**Comment by JDLENL** [comment]
perhaps bubble particles while it's fermenting and the lack of particles combined with a closed lid indicates that fermentation is complete

**Comment by Mysitia** [comment]
> perhaps bubble particles while it's fermenting and the lack of particles combined with a closed lid indicates that fermentation is complete

Yes, that's exactly what I wanted.
Because I'm always out exploring, I often miss the beeps :(
