### ISSUE TITLE
Trellises do not accept fruit if only one in stack, but still consume item

### ISSUE THREAD

**Issue by JDLENL** [Heccology/Bountiful-Fares#14]
[Video of the bug](https://dl.dropboxusercontent.com/scl/fi/fsh49xf3ro6r2hegkvd9h/javaw_EeEDHGKYBh.mp4?rlkey=m6k60wbodzhqwfzgccyjusp7w&dl=0)

Trellises consume the item in your hand without planting if it is a stack of only one. With stack sizes over one, the item is planted normally.

**Comment by Hecco56** [comment]
Finally fixed this bug! Thank you so much!
