### ISSUE TITLE
Mod loads the Sheets class too early

### ISSUE THREAD

**Issue by Moofellow** [Heccology/Bountiful-Fares#18]
[crash-2024-05-16_14.04.53-server.txt](https://github.com/Heccology/Bountiful-Fares/files/15339824/crash-2024-05-16_14.04.53-server.txt)
[latest.log](https://github.com/Heccology/Bountiful-Fares/files/15339825/latest.log)

crash and latest.log for reference

loading the Sheets class too early causes incompatibilities with other mods and interferes with the registration of custom banner patterns and sherds

**Comment by Hecco56** [comment]
its most likely an issue with Sinytra Connector, not much I can do
I also cannot replicate it while using Sinytra Connector, this mod and supplementaries

**Comment by abby-cadabra** [comment]
Just want to add that I'm getting this same error with Supplementaries, Bountiful Fares and Sinytra. Hoping something can be done about it - this is a great mod and otherwise works great on Forge.

**Comment by Tsunamori74** [comment]
I'm getting the same error on regular Fabric, no connector involved. 1.20.1, BF version 1.2.1, Supp version 3.1.5, Fabric 0.16.9
