### ISSUE TITLE
When trying to load a server with Bountiful Fares, it tends to freeze at a certain percent. Even then, chunks tend to stop loading and the server softlocks.

### ISSUE THREAD

**Issue by LittleManDiscord** [Heccology/Bountiful-Fares#2]
[latest.log](https://github.com/Heccology/Bountiful-Fares/files/14810511/latest.log)

I'm if there's another mod that doesn't agree with Bountiful Fares but I've had a similar issue in the past with mods like Twigs.

**Comment by Hecco56** [comment]
Yeah, I discovered that Twigs and Etcetera both are incompatible. I can try and find a fix, but I can't promise I can resolve it.
