### ISSUE TITLE
Suggestion: Modrinth Feature List Needs Update & Question: Scorchkin Planting

### ISSUE THREAD

**Issue by LunaFabula** [Heccology/Bountiful-Fares#25]
**Suggestion**: There are a few things with the Feature List on the Modrinth page, such as not listing where you can find the Elderberries and the Passion Fruit as well as the Trellis recipes does not need "five sticks"... Those are only two of the most glaring things I've noticed.

**Question**: How in the blazes can you plant Scorchkin Seeds? I've tried in water (like Spongekin), I've tried on Magma Blocks (thinking they needed heat), I've tried on farmland.... Yet, I'm confused as to how to plant them. I've tried those in a creative mode world. (Also, this is not answered under the FAQ on the Modrinth page.)

**Comment by Hecco56** [comment]
I'll update the modrinth page, thanks for reminding me haha
Also scorchkins are not fully implemented yet and will be obtainable in the next release (they can be placed on the underside of blocks if you do want to check them out)

**Comment by LunaFabula** [comment]
You're welcome for the reminder.

Ah, okay, Scorchkins are like the "crimson vines" from the Nether or Hanging Roots - that's neat! (Please close this once you've updated the Modrinth page, or otherwise feel that it's done.)
